name: Release

on:
  push:
    branches:
      - master
      - main
      - release

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run box version
        id: release
        uses: docker://ambimax/semantic-release:latest

      - name: Test output
        run: |
          echo {{ steps.release.output.SEMANTIC_VERSION }}
          echo {{ steps.release.output.GIT_VERSION }}
